site_name: Bills Processing
site_description: Processing of Bills
site_author: Ilya Elkind

repo_url: https://github.com/ilya-cortex/billings-processing-repo
edit_uri: https://github.com/ilya-cortex/billings-processing-repo/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
